######################################################################
##
## Filename: Registro_TF.udo
## Created on: Sun Jun 07 13:33:03 Romance Daylight Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
