######################################################################
##
## Filename: TB_PCAdder.udo
## Created on: Tue Oct 21 12:15:04 Romance Daylight Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
