######################################################################
##
## Filename: TB_Sistema_Tolerancia.udo
## Created on: Mon Feb 09 18:25:46 Romance Standard Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
