######################################################################
##
## Filename: TB_Registro_TF.udo
## Created on: Thu Feb 12 13:20:55 Romance Standard Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
